export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
